const userActionType =  {
	GOOGLE_SIGN_IN_START:'GOOGLE_SIGN_IN_START',
	EMAIL_SIGN_IN_START:'EMAIL_SIGN_IN_START',
	SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
	SIGN_IN_FILURE:'SIGN_IN_FILURE',
	USER_SESSION_CHECK:'USER_SESSION_CHECK',
	SIGN_OUT_START:'SIGN_OUT_START',
	SIGN_OUT_SUCCESS:'SIGN_OUT_SUCCESS',
	SIGN_OUT_FILURE:'SIGN_OUT_FILURE',
	SIGN_UP_START:'SIGN_UP_START',
	SIGN_UP_SUCCESS:'SIGN_UP_SUCCESS',
	SIGN_UP_FILURE:'SIGN_UP_FILURE'
}

export  default userActionType;